#!/bin/bash
# Guardando as comparação em uma variável
comparacao=$(diff -qr /var/test/paginaDeCadastro /var/www/html/paginaDeCadastro | awk '{print $1}')
diferencas=$(diff -qr /var/test/paginaDeCadastro /var/www/html/paginaDeCadastro)
# Gerando as duas chaves
if [ -z $comparacao ]
then
echo IGUAL
else
echo DIFERENTE
# Reorganizando a pasta para voltar ao seu estado original
rm -r /var/www/html/paginaDeCadastro
unzip /var/test/original.zip -d /var/www/html/
rm /var/test/original.zip
cd /var/www/html/ && zip -r /var/test/original.zip ./* && zip -r /var/test/original.zip ./* && cd /var
cd /var/www/html/ && zip -r /var/test/copia.zip ./* && cd /var
sendemail -f luiz.sousa.silva@icen.ufpa.br -t jordanyluiz@gmail.com -u "AVISO DE SEGURANÇA!" -m "Os arquivos do site foram modificados por alguma atividade suspeita. As correções já foram feitas automaticamente.\n$diferencas" -s cupijo.ufpa.br:587 -xu luiz.sousa.silva@icen.ufpa.br -xp Jordy123456
fi
